name: Dismiss stale PR reviews based on ownership - with config
description: Dismiss all reviews that are stale. The staleness is decided based on changed files and Codeowners file.
author: Balvajs
branding:
  icon: 'git-pull-request'
  color: 'yellow'

inputs:
  ignore-files:
    required: false
    description: List of file patterns that should be ignored -> no review will be dismissed based on these files changes. The list is new line separated
  token:
    required: false
    description: GitHub token with permissions to read organization. Default is github.token
    default: ${{ github.token }}
  no-owner-action:
    required: false
    description: What should happen if some file doesn't have owner. Valid options are `"dismiss-all"` and `"dismiss-none"`
    default: dismiss-all
  force-push-action:
    required: false
    description: What should happen if the git diff couldn't be resolved due to force push. Valid options are `"dismiss-all"` and `"dismiss-none"`
    default: dismiss-all
  dismiss-only:
    required: false
    description: List of users and teams that should be dismissed if their files changed. If set, only reviews that belong to these owners will be dismissed. The list is new line separated.

runs:
  using: 'node20'
  main: 'dist/main.cjs'
